name: Hello Actions

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello, Jake! Workflow is running."

      - name: Check file exists
        run: test -f Trip_Summary.md && echo "File found"
